Case 2 (Java PRO)
hagen2006GIT/JavaPRO_exec-1 pull request #2
Opened 2024-06-25 07:16 UTC by hagen2006GIT

домашняя работа по заданию 2

2024-06-26 09:56 UTC, Alexandr056 requested changes
хорошая работа, но нужны корректировки

2024-06-26 09:56 UTC, Alexandr056 commented on src/test/java/org/example/StreamRunner.java
> +                    .map(it -> it + " ")
а зачем это?

2024-06-26 09:56 UTC, Alexandr056 commented on src/test/java/org/example/StreamRunner.java
> +                .min(Integer::compare)
тут получится что снова идет перебор элементов и сравнение по правилу описанному в Integer, можно проще
мы же знаем что уже отсортировали, ограничили 3 элементами, остается понять что взять findFirst… ? или еще как-то?)

2024-06-26 09:56 UTC, Alexandr056 commented on src/test/java/org/example/StreamRunner.java
> +                .limit(1)
не нужен

2024-06-26 09:56 UTC, Alexandr056 commented on src/test/java/org/example/StreamRunner.java
> +            .map(it -> it.getName()+"-"+it.getAge()+"-"+it.getPosition())
проще тогда уже описать toString в классе Person а тут его вызывать

2024-06-26 09:56 UTC, Alexandr056 commented on src/test/java/org/example/StreamRunner.java
> +// в мапе возраст в скобках добавил только для наглядности при оценки результата, алгоритм не аффектит
аффектит, вместо Person что будет в стриме? это ли нужно получить?
map у Вас преобразовывает объекты в стриме

2024-06-26 09:56 UTC, Alexandr056 commented on src/test/java/org/example/StreamRunner.java
> +        System.out.println("\n6. Самое длинное слово: "+longWords
пож-та не пишите таких сложных конкатенаций) это очень сложно читать

2024-06-26 09:56 UTC, Alexandr056 commented on src/test/java/org/example/StreamRunner.java
> +                .sorted(Comparator.comparingInt(String::length))
а зачем две сортировки?

2024-06-26 12:10 UTC, hagen2006GIT commented on src/test/java/org/example/StreamRunner.java
> +            .map(it -> it.getName()+"-"+it.getAge()+"-"+it.getPosition())
да, конечно, переделал через toString()

2024-06-26 12:11 UTC, hagen2006GIT commented on src/test/java/org/example/StreamRunner.java
> +                    .map(it -> it + " ")
действительно, лишнее. Поправил

2024-06-26 12:11 UTC, hagen2006GIT commented on src/test/java/org/example/StreamRunner.java
> +                .min(Integer::compare)
поправил

2024-06-26 12:12 UTC, hagen2006GIT commented on src/test/java/org/example/StreamRunner.java
> +                .limit(1)
поправил

2024-06-26 12:12 UTC, hagen2006GIT commented on src/test/java/org/example/StreamRunner.java
> +        System.out.println("\n6. Самое длинное слово: "+longWords
принято:)
привел в более читабельный вид

2024-06-26 12:21 UTC, hagen2006GIT commented on src/test/java/org/example/StreamRunner.java
> +// в мапе возраст в скобках добавил только для наглядности при оценки результата, алгоритм не аффектит
да, верно, будет String. Поправил

2024-06-26 12:48 UTC, hagen2006GIT commented on src/test/java/org/example/StreamRunner.java
> +                .sorted(Comparator.comparingInt(String::length))
разобрался с двойной сортировкой, поправил

2024-06-26 12:50 UTC, hagen2006GIT commented
поправил замечания по всем пунктам

2024-06-27 10:32 UTC, Alexandr056 approved these changes
отлично!

2024-06-27 12:05 UTC, merged